{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2018-19839",
  "public_date": "2018-12-04T09:29:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-19839"
    },
    {
      "reference": "https://github.com/sass/libsass/issues/2657"
    },
    {
      "reference": "https://github.com/sass/libsass/pull/2767"
    }
  ],
  "description": "In LibSass prior to 3.5.5, the function handle_error in sass_context.cpp allows attackers to cause a denial-of-service resulting from a heap-based buffer over-read via a crafted sass file.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "libsass",
      "release_patches": [
        {
          "release_name": "trusty",
          "status": "DNE",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": [
    {
      "package_name": "libsass",
      "upstream_links": [
        {
          "link": "https://github.com/sass/libsass/commit/2cabd116b95d67dcd9d44fcb936dee03f4fc71b9"
        }
      ]
    }
  ]
}
