{
  "public_data_at_usn": "2021-03-16T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2021-28210",
  "public_date": "2021-06-11T16:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28210"
    },
    {
      "reference": "https://github.com/tianocore/edk2/pull/1137"
    },
    {
      "reference": "https://ubuntu.com/security/notices/USN-4923-1"
    }
  ],
  "description": "An unlimited recursion in DxeCore in EDK II.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [
    {
      "bug": "https://bugzilla.tianocore.org/show_bug.cgi?id=1743"
    }
  ],
  "priority": "medium",
  "discovered_by": "Laszlo Ersek",
  "assigned_to": "mdeslaur",
  "patches": [
    {
      "package_name": "edk2",
      "release_patches": [
        {
          "release_name": "trusty",
          "status": "ignored",
          "note": "out of standard support"
        }
      ]
    }
  ],
  "upstreams": [
    {
      "package_name": "edk2",
      "upstream_links": [
        {
          "link": "https://github.com/tianocore/edk2/commit/b9bdfc72853fe97bd24401f8873ca61524dd2dc6"
        },
        {
          "link": "https://github.com/tianocore/edk2/commit/47343af30435302c087027177613412a1a83e919"
        }
      ]
    }
  ]
}
