[
  {
    "DefinitionID": "oval:org.debian:def:34053100898814347553811654166620087830",
    "Title": "CVE-2016-2512 python-django",
    "Description": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2016-2512",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2512",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": {
      "MoreInfo": "",
      "Date": "1000-01-01T00:00:00Z"
    },
    "AffectedPacks": [
      {
        "Name": "python-django",
        "Version": "1.9.4-1",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2016-2512",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2512"
      }
    ]
  }
]
