[
  {
    "DefinitionID": "oval:org.debian:def:84394003748986489966087354095613679424",
    "Title": "CVE-2021-3561 fig2dev",
    "Description": "An Out of Bounds flaw was found fig2dev version 3.2.8a. A flawed bounds check in read_objects() could allow an attacker to provide a crafted malicious input causing the application to either crash or in some cases cause memory corruption. The highest threat from this vulnerability is to integrity as well as system availability.",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2021-3561",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3561",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": {
      "MoreInfo": "",
      "Date": "1000-01-01T00:00:00Z"
    },
    "AffectedPacks": [
      {
        "Name": "fig2dev",
        "Version": "1:3.2.7a-5+deb10u4",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2021-3561",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3561"
      }
    ]
  }
]
