{
  "CveID": "CVE-2009-5011",
  "Scope": "local",
  "Description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
  "Package": [
    {
      "PackageName": "python-pyftpdlib",
      "Release": [
        {
          "ProductName": "bullseye",
          "Status": "resolved",
          "FixedVersion": "0.5.2-1",
          "Urgency": "not yet assigned",
          "Version": "1.5.4-2"
        }
      ]
    }
  ]
}
