[
  {
    "DefinitionID": "oval:com.ubuntu.eoan:def:201938590000000",
    "Title": "CVE-2019-3859 on Ubuntu 19.10 (eoan) - medium.",
    "Description": "An out of bounds read flaw was discovered in libssh2 before 1.8.1 in the _libssh2_packet_require and _libssh2_packet_requirev functions. A remote attacker who compromises a SSH server may be able to cause a Denial of Service or read data in the client memory.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2019-3859",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3859",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "libssh2",
        "Version": "1.8.0-2.1",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2019-3859",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3859"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-3859.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://www.libssh2.org/CVE-2019-3859.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/libssh2/libssh2/pull/315"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://lists.opensuse.org/opensuse-security-announce/2019-04/msg00102.html"
      }
    ]
  }
]
