{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2018-20797",
  "public_date": "2019-02-27T17:29:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20797"
    },
    {
      "reference": "https://sourceforge.net/p/podofo/tickets/34/"
    }
  ],
  "description": "An issue was discovered in PoDoFo 0.9.6. There is an attempted excessive memory allocation in PoDoFo::podofo_calloc in base/PdfMemoryManagement.cpp when called from PoDoFo::PdfPredictorDecoder::PdfPredictorDecoder in base/PdfFiltersPrivate.cpp.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [
    {
      "bug": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923415"
    }
  ],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "libpodofo",
      "release_patches": [
        {
          "release_name": "focal",
          "status": "needs-triage",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": []
}
