[
  {
    "DefinitionID": "oval:com.ubuntu.bionic:def:2018207430000000",
    "Title": "CVE-2018-20743 on Ubuntu 18.04 LTS (bionic) - medium.",
    "Description": "murmur in Mumble through 1.2.19 before 2018-08-31 mishandles multiple concurrent requests that are persisted in the database, which allows remote attackers to cause a denial of service (daemon hang or crash) via a message flood.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2018-20743",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20743",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "mumble",
        "Version": "",
        "Arch": "",
        "NotFixedYet": true,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2018-20743",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20743"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2018/CVE-2018-20743.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/mumble-voip/mumble/issues/3505"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/mumble-voip/mumble/pull/3510"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/mumble-voip/mumble/pull/3512"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://bugs.debian.org/919249"
      },
      {
        "Source": "Bug",
        "RefID": "",
        "RefURL": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919249"
      }
    ]
  }
]
