{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2019-14492",
  "public_date": "2019-08-01T17:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14492"
    },
    {
      "reference": "https://github.com/opencv/opencv/compare/33b765d...4a7ca5a"
    },
    {
      "reference": "https://github.com/opencv/opencv/compare/371bba8...ddbd10c"
    },
    {
      "reference": "https://github.com/opencv/opencv/issues/15124"
    }
  ],
  "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
  "ubuntu_description": "It was discovered that OpenCV incorrectly handled certain files. An attaacker could possibly use this issue to cause a denial of service.",
  "notes": [],
  "bugs": [],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "opencv",
      "release_patches": [
        {
          "release_name": "eoan",
          "status": "ignored",
          "note": "reached end-of-life"
        }
      ]
    }
  ],
  "upstreams": [
    {
      "package_name": "opencv",
      "upstream_links": [
        {
          "link": "https://github.com/opencv/opencv/commit/321c74ccd6077bdea1d47450ca4fe955cb5b6330"
        }
      ]
    }
  ]
}
