[
  {
    "DefinitionID": "oval:com.ubuntu.xenial:def:201996420000000",
    "Title": "CVE-2019-9642 on Ubuntu 16.04 LTS (xenial) - medium.",
    "Description": "An issue was discovered in proxy.php in pydio-core in Pydio through 8.2.2. Through an unauthenticated request, it possible to evaluate malicious PHP code by placing it on the fourth line of a .php file, as demonstrated by a PoC.php created by the guest account, with execution via a proxy.php?hash=../../../../../var/lib/pydio/data/personal/guest/PoC.php request. This is related to plugins/action.share/src/Store/ShareStore.php.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2019-9642",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9642",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2019-9642",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9642"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-9642.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/pydio/pydio-core/commits/develop/core/src/proxy.php"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://pydio.com/en/community/releases/pydio-core/pydio-core-pydio-enterprise-823-security-release"
      }
    ]
  }
]
